### ISSUE TITLE
Higher K value in first ~30 games

### ISSUE THREAD

**Issue by maracuja-juice** [dmamills/elo-rank#4]
In this implementation of ELO: https://github.com/iain/elo
they use a higher K value for players with less than 30 games. Do you do something similar here?
Or can you add something like this?

**Comment by dmamills** [comment]
This package doesn't support that. It only implements the core elo ranking function. Something like you are describing could be built using this package as a dependency. You would just build out a `Player` class that would hold an internal instance of the `elo` object, which would allow you to control the k-factor dynamically based on tracking games played.

I hope that helps!

**Comment by maracuja-juice** [comment]
Okay when I come around to implement that I will do it like this probably.
Would it need a lot time or breaking changes to implement it into this package then?

**Comment by dmamills** [comment]
I don't think that it's too much extra work. But I think it'd be preferable to keep them as separate packages.
